# Generated by Django 5.0.6 on 2024-05-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('dependants', models.IntegerField()),
                ('coApplicantIncome', models.IntegerField()),
                ('loanAmt', models.IntegerField()),
                ('loanTerm', models.IntegerField()),
                ('creditHistory', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('married', models.CharField(max_length=15)),
                ('graduatedEducation', models.CharField(max_length=15)),
                ('selfEmployed', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=15)),
            ],
        ),
    ]
