# Generated by Django 5.0.6 on 2024-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankloanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='area',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='coApplicantIncome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approval',
            name='creditHistory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approval',
            name='dependants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approval',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='graduatedEducation',
            field=models.CharField(choices=[('Graduated', 'Graduated'), ('Not_Graduated', 'Not_Graduated')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='loanAmt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approval',
            name='loanTerm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approval',
            name='married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='selfEmployed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15),
        ),
    ]
